package com.common.system.mapper;

import com.common.system.entity.OverGoodsStock;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OverGoodsStockMapper {
    List<OverGoodsStock> queryOverGoodsStock();
    int addOverGoodsStock(@Param("goodsName") String goodsName,@Param("specifications") String specifications,@Param("intakeDirection") String intakeDirection,@Param("stockWarehouse") String stockWarehouse,@Param("nums") int nums,@Param("operator") String operator,@Param("remarks")  String remarks,@Param("pressure") String pressure ,@Param("valveSupplier") String valveSupplier,@Param("valveName") String valveName,@Param("valveSpecifications") String valveSpecifications,@Param("controlMainboardSupplier") String controlMainboardSupplier,@Param("controlMainboardName") String controlMainboardName,@Param("controlMainboardSpecifications") String controlMainboardSpecifications,@Param("version") String version,@Param("telMainBoardSupplier") String telMainBoardSupplier,@Param("telMainBoardName")String telMainBoardName,@Param("telMainBoardSpecifications") String telMainBoardSpecifications,@Param("telType") String telType,@Param("fourSupplier") String fourSupplier,@Param("fourMainBoardName") String fourMainBoardName,@Param("fourSpecifications")String fourSpecifications,@Param("telProtocol")String telProtocol);
    List<OverGoodsStock> serchOverGoodsStock(@Param("goodsName") String goodsName,@Param("specifications") String specifications,@Param("intakeDirection") String intakeDirection,@Param("operator") String operator, @Param("startDate") String startDate ,@Param("endDate") String endDate);
    List<OverGoodsStock> queryExist(@Param("goodsName") String goodsName,@Param("specifications") String specifications,@Param("intakeDirection") String intakeDirection,@Param("pressure") String pressure ,@Param("valveSupplier") String valveSupplier,@Param("valveName") String valveName,@Param("valveSpecifications") String valveSpecifications,@Param("controlMainboardSupplier") String controlMainboardSupplier,@Param("controlMainboardName") String controlMainboardName,@Param("controlMainboardSpecifications") String controlMainboardSpecifications,@Param("version") String version,@Param("telMainBoardSupplier") String telMainBoardSupplier,@Param("telMainBoardName")String telMainBoardName,@Param("telMainBoardSpecifications") String telMainBoardSpecifications,@Param("telType") String telType,@Param("fourSupplier") String fourSupplier,@Param("fourMainBoardName") String fourMainBoardName,@Param("fourSpecifications")String fourSpecifications,@Param("telProtocol")String telProtocol);
    int deleteGoodsStock(@Param("goodsName") String goodsName,@Param("specifications") String specifications,@Param("intakeDirection") String intakeDirection,@Param("nums") int nums,@Param("operator") String operator,@Param("pressure") String pressure ,@Param("valveSupplier") String valveSupplier,@Param("valveName") String valveName,@Param("valveSpecifications") String valveSpecifications,@Param("controlMainboardSupplier") String controlMainboardSupplier,@Param("controlMainboardName") String controlMainboardName,@Param("controlMainboardSpecifications") String controlMainboardSpecifications,@Param("version") String version,@Param("telMainBoardSupplier") String telMainBoardSupplier,@Param("telMainBoardName")String telMainBoardName,@Param("telMainBoardSpecifications") String telMainBoardSpecifications,@Param("telType") String telType,@Param("fourSupplier") String fourSupplier,@Param("fourMainBoardName") String fourMainBoardName,@Param("fourSpecifications")String fourSpecifications,@Param("telProtocol")String telProtocol);
    int updateGoodsStock(@Param("goodsName") String goodsName,@Param("specifications") String specifications,@Param("intakeDirection") String intakeDirection,@Param("nums") int nums,@Param("operator") String operator,@Param("pressure") String pressure ,@Param("valveSupplier") String valveSupplier,@Param("valveName") String valveName,@Param("valveSpecifications") String valveSpecifications,@Param("controlMainboardSupplier") String controlMainboardSupplier,@Param("controlMainboardName") String controlMainboardName,@Param("controlMainboardSpecifications") String controlMainboardSpecifications,@Param("version") String version,@Param("telMainBoardSupplier") String telMainBoardSupplier,@Param("telMainBoardName")String telMainBoardName,@Param("telMainBoardSpecifications") String telMainBoardSpecifications,@Param("telType") String telType,@Param("fourSupplier") String fourSupplier,@Param("fourMainBoardName") String fourMainBoardName,@Param("fourSpecifications")String fourSpecifications,@Param("telProtocol")String telProtocol);
}
